- name: Install dependencies
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Run ansible galaxy
      command: ansible-galaxy install -r requirements.yml
      register: galaxy_result
      changed_when: '"was installed successfully" in galaxy_result.stdout'

- name: Execute Flyway migration
  hosts: migration
  vars:
    fw_version: 6.0.1
  tasks:
    - name: Install python3-lxml
      become: true
      apt:
        name: python3-lxml
        update_cache: yes

- name: Docker
  hosts: app
  tasks:
    - block:
        - name: Install Docker
          include_role:
            name: ansible-role-docker
          vars:
            docker_install_compose: false
            docker_users:
              - '{{ ansible_ssh_user }}'
      become: true

    - name: Run app
      become: true
      shell: 'docker start app || docker run --name app -d -p 8080:8080 moleksyuk/demo --spring.datasource.url=jdbc:mysql://{{ db_host }}:{{ db_port }}/{{ db_name }} --spring.datasource.username={{ db_user }} --spring.datasource.password={{ db_password }}'
